// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwszmswhczsdanzavaji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3c3ptc3doY3pzZGFuemF2YWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTg0NzksImV4cCI6MjA2MTc3NDQ3OX0.dYjtvKZVEbiIWDY_L_cTpeOOOzdHpp3D6lWYvyNc61s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);